blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/leandrocanabarro/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Check the development guide for setup instructions
  - name: 💬 General Questions
    url: https://github.com/leandrocanabarro/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and get help from the community